<?php
class JConfig {
	public $offline = '0';
	public $offline_message = 'Diese Website ist zurzeit im Wartungsmodus.<br />Bitte später wiederkommen.';
	public $display_offline_message = '1';
	public $offline_image = '';
	public $sitename = 'smiley-homes.at';
	public $editor = 'tinymce';
	public $captcha = '0';
	public $list_limit = '20';
	public $access = '1';
	public $debug = '0';
	public $debug_lang = '0';
	public $dbtype = 'mysql';
	public $host = 'localhost';
	public $user = 'root';
<<<<<<< HEAD
	public $password = 'UVGL0001';
=======
	public $password = 'UVGL0001'; 
>>>>>>> master
	public $db = 'db17958_smiley-homes';
	public $dbprefix = 'lqstn_';
	public $live_site = '';
	public $secret = 'vo1ZyhSWxOU08zDf';
	public $gzip = '0';
	public $error_reporting = 'default';
	public $helpurl = 'http://help.joomla.org/proxy/index.php?option=com_help&keyref=Help{major}{minor}:{keyref}';
	public $ftp_host = '';
	public $ftp_port = '';
	public $ftp_user = '';
	public $ftp_pass = '';
	public $ftp_root = '';
	public $ftp_enable = '0';
	public $offset = 'UTC';
	public $mailonline = '1'; 
	public $mailer = 'mail';
	public $mailfrom = 'victor@victorgil.name';
	public $fromname = 'smiley-homes.at';
	public $sendmail = '/usr/sbin/sendmail';
	public $smtpauth = '0';
	public $smtpuser = '';
	public $smtppass = '';
	public $smtphost = 'localhost';
	public $smtpsecure = 'none';
	public $smtpport = '25';
	public $caching = '0';
	public $cache_handler = 'file';
	public $cachetime = '15';
	public $MetaDesc = 'smiley homes zirl wohnungen mieten qualität tirol innsbruck';
	public $MetaKeys = '';
	public $MetaTitle = '1';
	public $MetaAuthor = '1';
	public $MetaVersion = '0';
	public $robots = '';
	public $sef = '1';
	public $sef_rewrite = '1';
	public $sef_suffix = '0';
	public $unicodeslugs = '0';
	public $feed_limit = '10';
	public $log_path = 'C:\\xampp\\htdocs\\smiley-homes/logs';
	public $tmp_path = 'C:\\xampp\\htdocs\\smiley-homes/tmp';
	public $lifetime = '15';
	public $session_handler = 'database';
	public $MetaRights = '';
	public $sitename_pagetitles = '0';
	public $force_ssl = '0';
	public $frontediting = '1';
	public $feed_email = 'author';
	public $cookie_domain = '';
	public $cookie_path = '';
	public $asset_id = '1';
}